import type { SkillManifest } from "../skillTypes.js";

export const generalCodeReview: SkillManifest = {
  id: "general-code-review",
  name: "普适代码审查",
  version: "1.0.0",
  requirementPatterns: ["frontend-only", "cross-stack", "interaction", "unclear"],
  scopes: ["frontend", "backend", "fullstack"],
  match: {
    keywords: ["修改", "实现", "新增", "修复", "重构", "测试", "单元测试", "接口", "页面", "组件", "API", "schema", "model", "service", "bug", "feature"],
    fileGlobs: [
      "src/**/*.ts",
      "src/**/*.tsx",
      "src/**/*.js",
      "src/**/*.jsx",
      "backend/**/*.ts",
      "backend/**/*.js",
      "frontend/**/*.ts",
      "frontend/**/*.tsx",
      "frontend/**/*.js",
      "frontend/**/*.jsx",
      "**/*.test.ts",
      "**/*.test.tsx",
      "**/*.test.js",
      "**/*.test.jsx",
      "**/*.spec.ts",
      "**/*.spec.tsx",
      "**/*.spec.js",
      "**/*.spec.jsx",
    ],
    routeHints: ["src", "components", "routes", "services", "models", "controllers", "utils", "tests"],
  },
  steps: {
    code_review: {
      instructionAddon: [
        "普适代码审查 Skill 已激活：从代码交付质量角度审查生成结果。",
        "必须基于真实 diff / filesChanged 审查，不要凭空评价未变更文件。",
        "优先级：功能正确性 > 数据/接口契约 > 安全和副作用 > 测试覆盖 > 可维护性 > 风格。",
        "检查 testRequired=true 的任务是否有对应测试文件，diff 中是否包含测试。",
        "必须评估变更是否真的接入现有运行链路：页面需求要接入当前路由实际 import 的页面组件；服务/状态/工具函数要有真实调用点；测试要覆盖真实入口。",
        "严禁通过新建平行文件、平行页面、未被路由引用的组件、未被调用的 helper、未挂载的 Provider 等方式制造“看似完成”的伪接入。",
        "如果 diff 新增 routes/Foo.jsx，但项目实际入口引用 routes/Foo/Foo.jsx，必须给 blocker/major finding，指出新增文件没有被路由使用。",
        "不要要求无意义的测试；只指出会影响信心的缺口。",
        "重点识别常见低质量代码：调试注释/临时 TODO 未删除、console/debugger 残留、未使用变量/幽灵函数、死分支、只新增代码但未接入调用链、平行页面/平行组件伪接入、测试没有有效断言、mock 掩盖真实逻辑、硬编码临时值、类型 any/类型绕过、无关格式化或大范围重构。",
        "few-shot: 如果 diff 新增 helper 但没有任何调用点，finding={severity:\"major\", title:\"新增逻辑未接入调用链\", detail:\"变更新增了函数但用户可见路径没有调用它，验收标准无法达成\", recommendation:\"在对应页面/服务路径接入该函数并补充测试\"}。",
        "few-shot: 如果 diff 新增 frontend/src/routes/Article.jsx，但入口仍 import frontend/src/routes/Article/Article.jsx，finding={severity:\"blocker\", title:\"新增页面未接入真实路由\", detail:\"变更新增了平行 Article 页面，但当前应用路由实际渲染的是 routes/Article/Article.jsx，用户访问文章页不会触发新增逻辑\", recommendation:\"删除平行页面，把功能接入真实路由绑定组件，并确保 helper/component 被 import 和使用\"}。",
        "few-shot: 如果 diff 新增组件/Provider/服务方法，但没有在页面、路由、状态树或 API 调用链中接入，finding={severity:\"major\", title:\"变更存在伪接入\", detail:\"新增代码没有进入用户实际操作路径，无法证明需求已交付\", recommendation:\"沿现有入口把新增能力接入真实调用链，并用测试覆盖该入口\"}。",
        "few-shot: 如果测试只 render 组件但没有断言新增行为，finding={severity:\"minor\", title:\"测试未验证新增能力\", detail:\"测试没有断言新增字段/状态/边界结果，无法证明本次需求已交付\", recommendation:\"补充针对新增行为和边界输入的断言\"}。",
        "few-shot: 如果 diff 中存在 TODO/console/debugger 且非必要，finding={severity:\"nit\", title:\"调试残留未清理\", detail:\"交付代码中保留了临时调试信息，增加维护噪音\", recommendation:\"删除临时调试语句或改为正式错误处理\"}。",
        "blocker/major 需要给出可执行修复建议。",
        "不要输出长源码，不要重复 diff。",
      ].join("\n"),
      outputContractAddon: "findings 必须按严重程度排序。reviewedFiles 必须来自真实变更。decision 只能在无 blocker/major 时 approve。",
      confirmationPolicyAddon: {
        mode: "force-manual",
        reason: "代码审查涉及质量判断，默认需要用户确认。",
        requireHumanWhen: ["risk-present", "writes-files"],
        confidenceFloor: 0.7,
      },
    },
  },
};
