import { mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { describe, expect, it, vi } from "vitest";
import type { RepositoryScanResult } from "../domain/workspace.js";
import { createQuickProjectWorkspace, deriveRepoName, importWorkspace, isValidGitUrl } from "./workspaceService.js";

vi.mock("../agents/repositoryContextAgent.js", () => ({
  generateAgentReadme: vi.fn(async (repoName: string, scan: RepositoryScanResult) => ({
    fileName: "readme-for-agent.md",
    sections: {
      architecture: `Agent architecture for ${repoName}`,
      stack: scan.stack,
      conventions: ["Use JSON between steps"],
      testing: scan.testEntrypoints,
      riskNotes: scan.notes.length ? scan.notes : ["No risk notes"],
    },
    content: `# ${repoName} Agent Context\n\nGenerated by Repository Context Agent`,
  })),
}));

describe("workspaceService", () => {
  it("validates git urls and local paths", () => {
    expect(isValidGitUrl("https://github.com/TonyMckes/conduit-realworld-example-app.git")).toBe(true);
    expect(isValidGitUrl("git@github.com:TonyMckes/conduit-realworld-example-app.git")).toBe(true);
    expect(isValidGitUrl("not a repo")).toBe(false);
  });

  it("derives repository names", () => {
    expect(deriveRepoName("https://github.com/TonyMckes/conduit-realworld-example-app.git")).toBe("conduit-realworld-example-app");
  });

  it("creates quick project workspace with readme-for-agent", async () => {
    const workspace = await createQuickProjectWorkspace({
      title: "AI Blog Builder",
      description: "生成一个博客系统",
      stackPreference: "react-node",
    });

    expect(workspace.mode).toBe("quick-project");
    expect(workspace.agentReadme.fileName).toBe("readme-for-agent.md");
    expect(workspace.agentReadme.content).toContain("Generated by Repository Context Agent");
  });

  it("scans a local repository path", async () => {
    const repoPath = await mkdtemp(path.join(tmpdir(), "workspace-service-test-"));
    await writeFile(path.join(repoPath, "package.json"), JSON.stringify({
      scripts: { dev: "vite", test: "vitest run" },
      dependencies: { react: "latest", vite: "latest" },
      devDependencies: { vitest: "latest", typescript: "latest" },
    }));
    await writeFile(path.join(repoPath, "README.md"), "# Demo");
    await writeFile(path.join(repoPath, "main.ts"), "export const demo = true;\n");

    const workspace = await importWorkspace({ repoUrl: repoPath });

    expect(workspace.mode).toBe("repo-import");
    expect(workspace.workspaceDir).toBe(repoPath);
    expect(workspace.repositoryScan.source).toBe("local");
    expect(workspace.repositoryScan.stack).toEqual(expect.arrayContaining(["React", "Vite", "Vitest", "TypeScript"]));
    expect(workspace.repositoryScan.fileTree).toEqual(expect.arrayContaining(["README.md", "main.ts", "package.json"]));
    expect(workspace.repositoryScan.keyFiles).toHaveProperty("README.md");
    expect(workspace.agentReadme.content).toContain("Generated by Repository Context Agent");
  });

  it("rejects workspace import when remote clone fails", async () => {
    await expect(importWorkspace({ repoUrl: "https://github.com/example/not-a-real-repository-for-agent.git" }))
      .rejects
      .toThrow("仓库克隆失败");
  });
});
